  
  /* بنحط كل حاجة جوا ال كمبونانتس جوا الكونفيجراشين دا */
  
  export const configration ={
  header :{
    heading:"A FREE AND SIMPLE LANDING PAGE",
    headingInfo:"Namari is a free landing page template you can use for your projects. It is free to use for your  personal and commercial projects, enjoy!",
    buttoninfo:"START CREATING TODAY",
    link :"\Home"
  } ,
  /* دا الحاجات اللى جوا الكومبونينت بتاعت ال سيرفيس 
  contentService :{
    breafly :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut",
    breafFter :"— John Doe, Happy Customer",
    sectHead :"BELIEVING",
    sec2Head :"Focusing On What Matters Most",
    info:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam!" ,
    info2 :"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitaedicta sunt explicabo.",
    info3 :"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quiaconsequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet!",
    img :"../assets/images/dancer.jpg" ,
  } ,*/

  intro:{
    tagline :"SUCCESS",
    title:"How We Help You To Sell Your Product",
    description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam!",
    features:[
      {
        icone:"html5" ,title:" HTML5 &amp; CSS3", description :"Has ne tritani atomorum conclusionemque, in dolorum volumus cotidieque eum. At vis choro  neglegentur iudico"
      },
      {
        icone:"bolt" ,title:"Easy to Use ", description :"Cu vero ipsum vim, doctus facilisi sea in. Eam ex falli honestatis repudiandae, sit detracto mediocrem disputationi"
      },
      {
        icone:"tablet" ,title:"Fully Responsive", description :"Id porro tritani recusabo usu, eum intellegam consequuntur et. Fugit debet ea sit, an pro nemore vivendum"
      },
      {
        icone:"rocket" ,title:"Parallax Effect ", description :"Id porro tritani recusabo usu, eum intellegam consequuntur et. Fugit debet ea sit, an pro nemore vivendum"
      }
    ]

  },
  services:{
    tagline :"BELIEVING",
    title:"Focusing On What Matters Most",
    description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam!",
    

  },
  prices:{
    tagline :"YOUR CHOICE ",
    title:"We have the right package for you",
    blocks:[
      { title:'Personal' , firstdes:'The standard version' ,pricelogo:'$' ,price2:'19' ,secdesc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit' ,
       feature1:'5 Downloads' ,feature2:'2 Extensions',feature3:'Tutorials',feature4:'Forum Support',feature5:'1 year free updates',button:"BUY TODAY"},
      { title:'Student' , firstdes:'Most popular choice' ,pricelogo:'$' ,price2:'29' ,secdesc:'Lorem ipsum dolor sit amet, consectetur adipiscing elit' , 
      feature1:'15 Downloads' ,feature2:'2 Extensions',feature3:'Tutorials with Files',feature4:'Forum Support',feature5:'2 years free updates' ,button:"BUY TODAY",featured:'true'},
      { title:'developers' , firstdes:'Most popular choice' ,pricelogo:'$' ,price2:'49' ,secdesc:'Lorem ipsum dolor sit am' ,
       feature1:'Unlimited Downloads' ,feature2:'Unlimited Extensions',feature3:'HD Video Tutorials',feature4:'Chat Support',feature5:'Lifetime free updates',button:"BUY TODAY"}
    ]
    

  },
  clients:{
    tagline:"TRUST",
    title:"Companies who use our services",
    description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doeiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam!",

    images:[ 
      { src:'company-logo1.png', overlay:'Tree'},
      { src:'company-logo2.png', overlay:'Fingerprint'},
      { src:'company-logo3.png', overlay:'The Man'},
      { src:'company-logo4.png', overlay:'Mustache'},
      { src:'company-logo5.png', overlay:'Goat'},
      { src:'company-logo6.png', overlay:'Justice'},
      { src:'company-logo7.png', overlay:'Ball'},
      { src:'company-logo8.png', overlay:'Cold'},
      { src:'company-logo9.png', overlay:'Cold'},
    ]
  },

    
  gallery:{
    images:[
     'gallery-image-1.jpg','gallery-image-2.jpg','gallery-image-3.jpg','gallery-image-4.jpg','gallery-image-5.jpg'
     ,'gallery-image-6.jpg'
      
    ]

  },
  testomonials:{
    tagline :"FEEDBACK",
    title:"What our customers are saying",
    features:[
      {imag:'user-1.jpg' ,description :"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utlaboreet dolore magna aliqua " , footer:"John Doe - Happy Customer"},
      {imag:'user-2.jpg' ,description :" Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore" , footer:"Roslyn Doe - Happy Customer"},
      {imag:'user-3.jpg' ,description :" Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt utlabore" , footer:"Thomas Doe - Happy Customer"},
      
    ]

  },


  };